plugins:
  - jekyll-seo-tag
  
# Site settings
title: École de Piano de Sydney
description: Classical piano lessons for Dundas, Epping, Eastwood, Ermington, Newington, and Ryde regions 
# baseurl: "/ecolepianosydney.com" # the subpath of your site, e.g. /blog
# url: "https://juliana1109.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: École de Piano de Sydney
user_description: École de Piano de Sydney is a piano school dedicated to motivate and inspire students with high-quality European classical music instruction.
user_title: Piano lessons for Dundas, Epping, Eastwood, Ermington, Newington, and Ryde regions

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
