plugins:
  - jekyll-seo-tag
  
# Site settings
title: Premium Classical Music School
description: Piano, Violin, Viola, Cello, Flute, Classical guitar for Dundas, Epping, Eastwood, Ermington, and Newington regions in Sydney 
# baseurl: "/ecolepianosydney.com" # the subpath of your site, e.g. /blog
# url: "https://juliana1109.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ecole Music Sydney
user_description: Ecole Music Sydney is a Premium Classical Music School to provide students of all ages with high standards of music education based on our systemized teaching methods. 
user_title: Piano, Violin, Viola, Cello, Flute, Classical guitar for Dundas, Epping, Eastwood, Ermington, and Newington regions in Sydney

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
